config/routes.rb
Simplepage::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope "(:locale)", :locale => /en|ru/ do
    root :to => 'home#index'
    resources :sites do
      resources :stylesheets
      resources :javascripts
      resources :pages
      resources :templates
      resources :layouts
      resources :images
      resources :files
    end

    resources :forms do
      resources :submits
      resources :fields
    end

    resources :users do
      member do
        get :activate
      end
    end

    resources :sessions
    resources :resets
    resources :news, :only => [:index, :show]
    resources :reviews, :only => [:index, :create]

    resources :themes, only: [:show]

    get "login" => "sessions#new", :as => "login"
    post "logout"=> "sessions#destroy", :as => "logout"

    get 'contact_us' => "home#contact_us", as: 'contact_us'

    get   "submit/success"  => "submits#success", as: 'submit_success'
    post  "submit/:uuid"    => "submits#create"

    get 'help'  => "home#help", as: 'help'
    get 'rules' => "home#rules", as: 'rules'
  end

  namespace :api do
    resources :sites, only: [] do
      resources :templates, only: [] do
        post 'update', on: :collection
      end
    end
  end
end

app/views/templates/_form.html.slim
= simple_form_for [@site, @template], url: @template.locale_path, html: { id: 'code_form' } do |f|
  .field
    = f.input :name
    = f.label :content
    - if @parent
        = f.hidden_field :parent_id, value: @parent.id
    .code
      = f.text_area :content, id: "code_content"
  = f.submit t('save'), class: 'btn'

app/views/templates/_list.html.slim
.tree
  - if @template
    span.path
      =t('document.path')
      = link_to ' ~ ', site_templates_path(@locale, @site)
      |/
      - file_tree(@template).each do |t|
        = link_to t.name, site_template_path(@locale, @site, t)
        |/
    hr

.files-nav
  .pull-right
    i.icon-plus
    |&nbsp;
    a#add-folder href='#' data={toggle: 'modal',  target: '.add-template-folder' }
      = t('document.add_folder')
  .clearfix

- if @templates.length > 0
  table.table.table-striped
    - @templates.each do |template|
      tr
        td
          - if template.folder
            = link_to site_template_path(@locale, @site.id, template.id) do
              i.icon-folder-open
            |&nbsp;
            = link_to site_template_path(@locale, @site.id, template.id) do
              = template.name
          - else
            = link_to edit_site_template_path(@locale, @site.id, template.id) do
              = template.name
        td
          .text-right
            = link_to site_template_path(@locale, @site, template), class: 'pad', data: { toggle: 'tooltip' }, title: t('overview'), rel: 'tooltip' do
              i.icon-tasks
            = destroy_link_to site_template_path(@locale, @site.id, template)

= link_to t('template.new'), new_site_template_path(@locale, @site.id, (@template ? { parent_id: @template.id } : nil)), class: 'btn btn-primary'

= render 'templates/modal_add_folder'

app/views/templates/_modal_add_folder.html.slim
.add-template-folder.modal
  .modal-header
    button type="button" class="close" data={ dismiss: 'modal'} aria={ hidden: "true" }
      |×
    h3 =t('document.add_folder_title')
  =simple_form_for([@site, @site.templates.new],
    url: site_templates_path(@locale, @site),
    html: { class: 'slim' }) do |f|
    .modal-body
      = f.input :name
      - if @template
        = f.hidden_field :parent_id, value: @template.id
      = f.hidden_field :folder, value: true
    .modal-footer
      .pull-left
        = f.submit t('add_new_folder'), class: 'btn btn-primary'
      .pull-right
        = link_to t('cancel'), '#', id: 'close-add-folder', class: 'btn space', data: {dismiss: 'modal' }, 'aria-hidden' => 'true'

app/views/templates/edit.html.slim
= breadcrumb @breadcrumb, true

- if @template
    span.path
      =t('document.path')
      = link_to ' ~ ', site_templates_path(@locale, @site)
      |/
      - file_tree(@template)[0..-2].each do |t|
        = link_to t.name, site_template_path(@locale, @site, t)
        |/
    hr
h2 = t('edit')
= '[% include "'+file_tree(@template).map{|t| t.name}.join('/')+'" %]'
== render 'form'

app/views/templates/index.html.slim
= breadcrumb @breadcrumb

= render '/sites/tab'

app/views/templates/new.html.slim
= breadcrumb @breadcrumb, true
- if @parent
    span.path
      =t('document.path')
      = link_to ' ~ ', site_templates_path(@locale, @site)
      |/
      - file_tree(@template)[0..-2].each do |t|
        = link_to t.name, site_template_path(@locale, @site, t)
        |/
    hr
h2 = t('template.new')

== render 'form'

app/views/templates/show.html.slim
= breadcrumb @breadcrumb, true
/
  p
    'Name:
    = @template.name

  p
    'Created:
    = @template.created_at
  p
    'Last updated:
    = @template.updated_at
= render '/sites/tab'