config/routes.rb
Simplepage::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope "(:locale)", :locale => /en|ru/ do
    root :to => 'home#index'
    resources :sites do
      resources :stylesheets
      resources :javascripts
      resources :pages
      resources :templates
      resources :layouts
      resources :images
      resources :files
    end

    resources :forms do
      resources :submits
      resources :fields
    end

    resources :users do
      member do
        get :activate
      end
    end

    resources :sessions
    resources :resets
    resources :news, :only => [:index, :show]
    resources :reviews, :only => [:index, :create]

    resources :themes, only: [:show]

    get "login" => "sessions#new", :as => "login"
    post "logout"=> "sessions#destroy", :as => "logout"

    get 'contact_us' => "home#contact_us", as: 'contact_us'

    get   "submit/success"  => "submits#success", as: 'submit_success'
    post  "submit/:uuid"    => "submits#create"

    get 'help'  => "home#help", as: 'help'
    get 'rules' => "home#rules", as: 'rules'
  end

  namespace :api do
    resources :sites, only: [] do
      resources :templates, only: [] do
        post 'update', on: :collection
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :require_login
  def index
    #@total    = Site.count
    fill_home
  end
end

app/views/home/_carousel.html.slim
.carousel.slide#carousel
  ol.carousel-indicators
    li data-target="#carousel" data-slide-to="0" class="active"
    li data-target="#carousel" data-slide-to="1"
    li data-target="#carousel" data-slide-to="2"
    li data-target="#carousel" data-slide-to="3"
  .carousel-inner
    .item.active
      img src="/img/html.jpg" alt=""
      .carousel-caption
        h4
          ' Full code access
        p
          ' You can edit, delete or add any code what are you want.


    .item
      img src="/img/templates.jpg" alt=""
      .carousel-caption
        h4
          ' Template includes
        p
          ' You can choose the templates and layouts for you pages


    .item
      img src="/img/domain.jpg" alt=""
      .carousel-caption
        h4
          ' Your own domains
        p
          ' It is simple to use your own 2-level domains

    .item
      img src="/img/result.jpg" alt=""
      .carousel-caption
        h4
          ' Good results
        p
          ' Get the rapid results

  a class="left carousel-control" href="#carousel" data-slide="prev"
    ' &lsaquo;
  a class="right carousel-control" href="#carousel" data-slide="next"
    ' &rsaquo;

app/views/home/_dashboard.html.slim
.dashboard
  ul.nav.nav-list.text-right
    li.nav-header
      = t('nav.my_sites')
    - sites = current_user.sites.active.order("modified_at DESC").limit(3)
    - sites.each do |s|
      li
        = link_to s.full_name, site_pages_path(@locale, s)

    - if sites.length == 0
      = link_to t('site.create_new'), new_site_path(@locale)
    - else
      li
        small
          = link_to t('site.all'), sites_path(@locale)
    li.nav-header
        = t('nav.my_forms')

    - forms = current_user.forms.limit(3)
    - forms.each do |form|
      li
        = link_to form.name, form_path(@locale, form)

    - if forms.length == 0
      li
        = link_to t('form.create_new'), new_form_path(@locale)
    - else
      li
        small
          = link_to t('form.all'), forms_path(@locale)

app/views/home/_live.html.slim
- if @public.length > 0
  .live
    h2.pull-right Live
    .clearfix
    - @public.each do |s|
      div =link_to s.name, s.full_url
  p

app/views/home/_login.html.slim
.login-block
  ul.nav.nav-tabs#login
    li class="#{'active' unless flash[:user_creation_action]}"
      a href="#login_form"
        = t('nav.login')
    li class="#{'active' if flash[:user_creation_action]}"
      a href="#signup_form"
        = t('nav.sign_up')
    li.hide
      a href="#reset_form"
        = t('nav.reset_password')

  .tab-content
    #login_form.tab-pane class="#{'active' unless flash[:user_creation_action]}"
      = render '/sessions/form'
    #signup_form.tab-pane class="#{'active' if flash[:user_creation_action]}"
      - @user = User.new unless @user
      = render '/users/form'
    #reset_form.tab-pane
      = render '/resets/form'

app/views/home/_stats.html.slim
- if @stats
  .stats
    h2.pull-right Stats
    .clearfix
    div
      = t('stats.sites')
      = stats @stats[:sites]
    div
      = t('stats.pages')
      = stats @stats[:pages]
    div
      = t('stats.forms')
      = stats @stats[:forms]
    div
      = t('stats.javascripts')
      = stats @stats[:js]
    div
      = t('stats.stylesheets')
      = stats @stats[:css]
    div
      = t('stats.images')
      = stats @stats[:images]
    div
      = t('stats.templates')
      = stats @stats[:templates]
    div
      = t('stats.layouts')
      = stats @stats[:layouts]

app/views/home/contact_us.html.slim
<script src='https://www.google.com/recaptcha/api.js'></script>

.row
  .span8
    h1 Contact us
    p
      |Feel free to send us a <a href="mailto:support@simplepage.biz">letter</a>
    p
      |or fill the form:
    hr
    <form action='http://simplepage.biz/submit/26c047be-1490-404a-85fe-fc44a840c52e' accept-charset='UTF-8' method='post'>
    <label for='simpleform_1'>email:</label>
    <input type='text' id='simpleform_1' name='email' value=''/>
    <label for='simpleform_2'>name:</label>
    <input type='text' id='simpleform_2' name='name' value=''/>
    <label for='simpleform_3'>message:</label>
    <textarea name='message' id='simpleform_3' rows='5' columns='30'></textarea>
    <div class="g-recaptcha" data-sitekey="6LdoMB0UAAAAADQ0DnR3S8Fi1tcfsGY5Qb-SarAt"></div>
    <br/>
    <p><input type='submit' value='Submit' class='btn'/></p>
    </form>

app/views/home/help.html.slim
h1 Help

h2 Directives

h3 include
p It will include content of template
pre
  |[% include 'template_name' %]
p
  strong
    |Example
p Page: /
pre
  |[% include 'header' %]
  br
  |... page content ...
  br
  |[% include 'footer' %]
p Template: header
pre
  = '<html>'
  br
  = '<head><title>Title</title></head>'
  br
  = '<body>'
p Template: footer
pre
  = '</body>'
  br
  = '</html>'
p Result:
pre
  = '<html>'
  br
  = '<head><title>Title</title></head>'
  br
  = '<body>'
  br
  |... page content ...
  br
  = '</body>'
  br
  = '</html>'

h3 variable
p Variables subtitutions
pre
  |[% $variable='value' %]
  br
  |[% $variable %]
p
  strong
    |Example
p Page: /
pre
  |[% $title = 'Home Page' %]
  br
  |[% include 'header' %]
  br
  |... page content ...
  br
  |[% include 'footer' %]
p Template: header
pre
  = '<html>'
  br
  = '<head><title>[% $title %]</title></head>'
  br
  = '<body>'
p Template: footer
pre
  = '</body>'
  br
  = '</html>'
p Result:
pre
  = '<html>'
  br
  = '<head><title>Home Page</title></head>'
  br
  = '<body>'
  br
  |... page content ...
  br
  = '</body>'
  br
  = '</html>'
h3 layout, yield
p Layout using. We can set layout for page using 'layout' directive.
p Page content will insert into 'yield' place.
pre
  |[% layout 'layout_name' %]
  br
  |[% yield %]
p
  strong
    |Example
p Page: /
pre
  |[% $title = 'Home Page' %]
  br
  |[% layout 'first' %]
  br
  |... page content ...

p Layout: first
pre
  |[% include 'header' %]
  br
  |[% yield %]
  br
  |[% include 'footer' %]

p Template: header
pre
  = '<html>'
  br
  = '<head><title>[% $title %]</title></head>'
  br
  = '<body>'
p Template: footer
pre
  = '</body>'
  br
  = '</html>'
p Result:
pre
  = '<html>'
  br
  = '<head><title>Home Page</title></head>'
  br
  = '<body>'
  br
  |... page content ...
  br
  = '</body>'
  br
  = '</html>'

h3 image
p You can use image's name in code for get it's url.
pre
 |[% image:image_name %]
p
  strong
    |Example
p You uploaded an image 'company-logo.png' and set the image name to 'logo'.
p You can use the next code for insert image tag:
pre
  = '<img src="[% image:logo %]" alt="Logo"/>'

h3 file
p You can use file's name in code for get it's url.
pre
 |[% file:file_name %]
p
  strong
    |Example
p You uploaded a file 'offer.pdf'.
p You can use the next code for insert link to the document:
pre
  = '<a href="[% file:offer.pdf %]">View Offer</a>'

h2 Tricks
h3 404 error pages (not found)
p Create page with name 404 and this page will be render when no page found.

app/views/home/index.html.slim
.row
  .span8
    = render '/home/carousel'
  .span4
    - unless current_user
      = render :partial => '/home/login', :locals => {:flash => flash}
    - else
      = render '/home/dashboard'

.row
  .span8
    = render '/news/promo'
  .span4
    = render '/reviews/last'
    = render '/themes/active'
    = render '/home/stats'
    = render '/home/live'

app/views/home/rules.html.erb
<h1>Rules</h1>

<p>Not allowed:</p>
<ul>
  <li>Adult content</li>
  <li>Spam</li>
  <li>Auto/Follow/Followers/Subscribe Services</li>
  <li>Click Jacking</li>
  <li>Auto redirect to external domains</li>
</ul>