config/routes.rb
Simplepage::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope "(:locale)", :locale => /en|ru/ do
    root :to => 'home#index'
    resources :sites do
      resources :stylesheets
      resources :javascripts
      resources :pages
      resources :templates
      resources :layouts
      resources :images
      resources :files
    end

    resources :forms do
      resources :submits
      resources :fields
    end

    resources :users do
      member do
        get :activate
      end
    end

    resources :sessions
    resources :resets
    resources :news, :only => [:index, :show]
    resources :reviews, :only => [:index, :create]

    resources :themes, only: [:show]

    get "login" => "sessions#new", :as => "login"
    post "logout"=> "sessions#destroy", :as => "logout"

    get 'contact_us' => "home#contact_us", as: 'contact_us'

    get   "submit/success"  => "submits#success", as: 'submit_success'
    post  "submit/:uuid"    => "submits#create"

    get 'help'  => "home#help", as: 'help'
    get 'rules' => "home#rules", as: 'rules'
  end

  namespace :api do
    resources :sites, only: [] do
      resources :templates, only: [] do
        post 'update', on: :collection
      end
    end
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_filter :find_site
  before_filter :find_structure, only: [:index, :show]
  before_filter :find_user_file, only: [:update, :edit, :destroy, :show]

  def index
    breadcrumb('Files')
  end

  def show
    breadcrumb(@file.name)
    # overwrite
    @files = @site.documents.where(parent_id: @file.id).order('folder DESC, name')
  end

  def destroy
    @file.destroy
    if request.referer =~ /files/
      redirect_to :back
    else
      redirect_to site_files_path(@locale, @site)
    end
  end

  def create
    @file = @site.documents.new(params[:document])

    unless @file.save
      flash[:alert] = @file.errors.full_messages.join("; ")
    end
    if request.referer =~ /files/
      redirect_to :back
    else
      redirect_to site_files_path(@locale, @site)
    end
  end

  def edit
    breadcrumb(@file.name)
  end

  def update
    params[:document].delete(:parent_id) if params[:document] && params[:document][:parent_id]

    if @file.update_attributes(params[:document])
      redirect_to site_files_path(@locale, @site), :notice => 'Saved'
    else
      breadcrumb(@file.name)
      flash.now[:alert] = 'Error'
      render action: :edit
    end
  end

  private

  def find_user_file
    @file = @site.documents.find(params[:id])
  end

  def breadcrumb(last)
    base_breadcrumb(
      [
        ["Home", root_url(@locale)],
        ["My sites", sites_path(@locale)],
        [@site.full_name, site_path(@locale, @site)],
        ["Files", site_files_path(@locale, @site)]
      ], last)
  end
end

app/views/files/_form.html.slim
= simple_form_for [@site, @file], url: @file.locale_path do |f|
  = f.input :name
  = f.input :attachment

  = f.submit t('save'), :class => 'btn'

app/views/files/_list.html.slim
.tree
  - if @file
    span.path
      = t('document.path')
      = link_to ' ~ ', site_files_path(@locale, @site)
      |/
      - file_tree(@file).each do |f|
        = link_to f.name, site_file_path(@locale, @site, f)
        |/
    hr

.files-nav
  .pull-left
    i.icon-plus
    |&nbsp;
    a#add-file href='#' data={toggle: 'modal',  target: '.add-file' }
      = t('document.upload_files')
  .pull-right
    i.icon-plus
    |&nbsp;
    a#add-folder href='#' data={toggle: 'modal',  target: '.add-folder' }
      = t('document.add_folder')
  .clearfix

- if @files.length > 0
  table.table.table-striped
    - @files.each do |file|
      tr
        td
          - if file.folder
            = link_to site_file_path(@locale, @site.id, file.id) do
              i.icon-folder-open
              |&nbsp;
              = file.name
          - else
            = link_to edit_site_file_path(@locale, @site.id, file.id) do
              = file.name
        td
          .text-right
            - if file.attachment?
              = link_to file.full_url, class: 'pad', data: {toggle: 'tooltip'}, title: t('live'), rel: 'tooltip' do
                i.icon-globe
            - else
              = link_to "#", class: 'pad', data: {toggle: 'tooltip'}, title: t('no_file'), rel: 'tooltip' do
                i.icon-globe.icon-white
            = link_to site_file_path(@locale, @site, file), class: 'pad', data: { toggle: 'tooltip' }, title: t('overview'), rel: 'tooltip' do
              i.icon-tasks
            = destroy_link_to site_file_path(@locale, @site.id, file)

= render 'files/modal_add_folder'
= render 'files/modal_add_file'

app/views/files/_modal_add_file.html.slim
.add-file.modal
  .modal-header
    button type="button" class="close" data={ dismiss: 'modal'} aria={hidden: "true"}
      |×
    h3 =t('document.upload_file_title')
  = simple_form_for @site, url: site_path(@locale, @site), multipart: true, html: { id: 'upload_files', class: 'slim' }  do |f|
    .modal-body
      - if @file
        = f.hidden_field :parent_id, value: @file.id
      = f.input :files, as: :file, label: false, input_html: { multiple: true }
    .modal-footer
      .pull-left
        = f.submit t('add_new_files'), class: 'btn btn-primary'
      .pull-right
        = link_to t('cancel'), '#', id: 'close-add-file', class: 'btn space', data: {dismiss: 'modal' }, 'aria-hidden' => 'true'

app/views/files/_modal_add_folder.html.slim
.add-folder.modal
  .modal-header
    button type="button" class="close" data={ dismiss: 'modal'} aria={hidden: "true"}
      |×
    h3 =t('document.add_folder_title')
  = simple_form_for [@site, Document.new], url: site_files_path(@locale, @site), html: { class: 'slim' } do |f|
    .modal-body
      = f.input :name
      - if @file
        = f.hidden_field :parent_id, value: @file.id
      = f.hidden_field :folder, value: true
    .modal-footer
      .pull-left
        = f.submit t('add_new_folder'), class: 'btn btn-primary'
      .pull-right
        = link_to t('cancel'), '#', id: 'close-add-folder', class: 'btn space', data: {dismiss: 'modal' }, 'aria-hidden' => 'true'

app/views/files/edit.html.slim
= breadcrumb @breadcrumb, true

h2 = t('document.edit')

== render 'form'

app/views/files/index.html.slim
= breadcrumb @breadcrumb

= render '/sites/tab'

app/views/files/show.html.slim
= breadcrumb @breadcrumb, true
/
  p
    'Name:
    = @file.name
  p
    'URL:
    = @file.full_url
  p
    'Created:
    = @file.created_at
  p
    'Last updated:
    = @file.updated_at

= render '/sites/tab'