config/routes.rb
Simplepage::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope "(:locale)", :locale => /en|ru/ do
    root :to => 'home#index'
    resources :sites do
      resources :stylesheets
      resources :javascripts
      resources :pages
      resources :templates
      resources :layouts
      resources :images
      resources :files
    end

    resources :forms do
      resources :submits
      resources :fields
    end

    resources :users do
      member do
        get :activate
      end
    end

    resources :sessions
    resources :resets
    resources :news, :only => [:index, :show]
    resources :reviews, :only => [:index, :create]

    resources :themes, only: [:show]

    get "login" => "sessions#new", :as => "login"
    post "logout"=> "sessions#destroy", :as => "logout"

    get 'contact_us' => "home#contact_us", as: 'contact_us'

    get   "submit/success"  => "submits#success", as: 'submit_success'
    post  "submit/:uuid"    => "submits#create"

    get 'help'  => "home#help", as: 'help'
    get 'rules' => "home#rules", as: 'rules'
  end

  namespace :api do
    resources :sites, only: [] do
      resources :templates, only: [] do
        post 'update', on: :collection
      end
    end
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_filter :find_user_form, :only => [:destroy, :show, :edit, :update]

  def index
    breadcrumb('My Forms')

    @forms = current_user.forms#.order('modified_at DESC')
  end

  def new
    breadcrumb('New Form')
    @form = Form.new
  end

  def create
    @form = Form.new(params[:form])
    @form.user = current_user

    if @form.save
      redirect_to form_path(@locale, @form), notice: 'Form was successfully created.'
    else
      breadcrumb('New Form')
      flash.now[:alert] = 'Error'
      render action: "new"
    end
  end

  def update
    if @form.update_attributes(params[:form])
      redirect_to form_path(@locale, @form), notice: 'Form was successfully updated.'
    else
      breadcrumb(@form.name)
      flash.now[:alert] = 'Error'
      render action: "edit"
    end
  end

  def edit
    breadcrumb(@form.name)
  end

  def show
    breadcrumb(@form.name)
  end

  def destroy
    @form.destroy
    redirect_to forms_path(@locale), notice: 'Form was destroyed.'
  end

  private

  def find_user_form
    @form = current_user.forms.find(params[:id])
  end

  def breadcrumb(last)
    base_breadcrumb(
      [
        ["Home", root_url(@locale)],
        ["My Forms", forms_path(@locale)],
      ], last)
  end
end

app/views/forms/_form.html.slim
= simple_form_for @form, url: @form.locale_path, html: { id: 'form_data_form' } do |f|
  .field
    = f.input :name
    = f.input :notify_subject
    = f.input :redirect

  .actions
    - if @form.id
      = f.submit t('save'), class: 'btn'
    - else
      = f.submit t('create'), class: 'btn'

app/views/forms/edit.html.slim
= breadcrumb @breadcrumb

h2 = t('form.edit')

== render 'form'

app/views/forms/index.html.slim
= breadcrumb @breadcrumb

h2 My forms
- if @forms.length > 0
  table.table.table-striped
    tr
      th
        = t('form.name')
      th
        = t('form.submits')
      th
        '
    - @forms.each do |form|
      tr
        td
          = link_to form.name, form_path(@locale, form)
        td
          = link_to form.submits.length, form_submits_path(@locale, form)
        td
          .text-right
            = destroy_link_to form_path(@locale, form)
- else
  p
    = t('form.empty')
= link_to t('form.new'), new_form_path(@locale), class: 'btn btn-primary'

app/views/forms/new.html.slim
= breadcrumb @breadcrumb

h2 = t('form.new')

== render 'form'

app/views/forms/show.html.slim
= breadcrumb @breadcrumb

h2= @form.name
p =link_to t('edit'), edit_form_path(@locale, @form)
ul.nav.nav-tabs#structure
    li.active
      a href="#fields"
        = t('form.fields')
    li
      a href="#html"
        = t('form.html')
    li
      a href="#form"
        = t('form.form')

.tab-content
  .tab-pane.active#fields
    = simple_form_for [@form, Field.new], url: form_fields_path(@locale, @form) do |f|
      table.table

        - @form.fields.each do |field|
          tr
            td
              = field.name
            td
              = field.kind
            td
              = destroy_link_to form_field_path(@locale, @form, field)
        tr
          td
            = f.input :name, label: false
          td
            = f.input :kind, include_blank: false, label: false
          td
            = f.submit t('form.add_new_field'), class: 'btn'

  .tab-pane#html
    - html = "<form action='http://simplepage.biz/submit/#{@form.uuid}' accept-charset='UTF-8' method='post'>"
    - @form.fields.each do |field|
      p
        - html += "<label for='simpleform_#{field.id}'>#{field.name}:</label>"
      - if field.text?
        - html += "<input type='text' id='simpleform_#{field.id}' name='#{field.name}' value=''/>"
      - elsif field.select?
        - html += "<select name='#{field.name}' id='simpleform_#{field.id}'>"
        - html += "<option value='value 1'>Title for value 1</option>"
        - html += "<option value='value 2'>Title for value 2</option>"
        - html += "<option value='value 3'>Title for value 3</option>"
        - html += "</select>"
      - elsif field.textarea?
        - html += "<textarea name='#{field.name}' id='simpleform_#{field.id}' rows='5' columns='30'>"
        - html += "</textarea>"
      - else
        - html += "<input type='text' id='simpleform_#{field.id}' name='#{field.name}' value=''/>"
    - html += "<p><input type='submit' value='"+t('submit')+"'/></p>"
    - html += "</form>"
    = html

  .tab-pane#form
    == html